post_install() {
    echo "Ensure all of your existing .wad files use lowercase only, no UpperCase allowed.

Copy your existing .wad files to ~/.zandronum/:

    $ cp *.wad ~/.zandronum/

Run zandronum to initialize: (Click cancel after opens)

	$ zandroumium 

Copy zandronum.ini to ~/.zandronum/:

    $ cp /usr/share/games/brutaldoom/zandronum.ini ~/.zandronum/zandronum.ini

Good to go!"

}

post_upgrade() {
    post_install
}
